webtalk_init -webtalk_dir E:/Git/code/ECNURVCORE/ECNURVCORE/SIM/RVCORE_TEST/RVCORE_TEST.sim/sim_1/behav/xsim/xsim.dir/core_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 13 13:46:50 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dbbbc629-ae91-41ef-b064-90db1fe1c8b7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6413fe2ee69d44419382e62437256e1c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1600 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.38_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6224_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3473961546 -regid "" -xml E:/Git/code/ECNURVCORE/ECNURVCORE/SIM/RVCORE_TEST/RVCORE_TEST.sim/sim_1/behav/xsim/xsim.dir/core_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Git/code/ECNURVCORE/ECNURVCORE/SIM/RVCORE_TEST/RVCORE_TEST.sim/sim_1/behav/xsim/xsim.dir/core_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Git/code/ECNURVCORE/ECNURVCORE/SIM/RVCORE_TEST/RVCORE_TEST.sim/sim_1/behav/xsim/xsim.dir/core_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
